### ISSUE TITLE
Architekturprinzipen

### ISSUE THREAD

**Issue by FrankMoritz** [ehmkah/cas_swa_sad#6]
Jeder gibt bitte hier an, für welches Prinzip er sich entschieden hat.
- [ ] @FrankMoritz : Primacy of Principles
- [ ] @Krigu: Data Security
- [ ] @ye-zhao :Common Vocabulary and Data Definitions
- [x] @ehmkah : Common Use Applications 
- [ ] @johndilbert: Data Trustee

**Comment by ehmkah** [comment]
okay, ich habe mal mein Textchen hineingehämmert. Das mit dem Opensourceprinzip lasse ich lieber, will lieber noch mal rausgehen, als mir was aus den Fingern saugen ☀️ 🏊 🍺

**Comment by johndilbert** [comment]
huch der Dornröschenschlaf ist schon vorbei???
